### ISSUE TITLE
drawing confidence intervals properly

### ISSUE THREAD

**Issue by gbiele** [thomasp85/ggfx#13]
The idea to use blurs for confidence intervals is great. But I fear result shown here : https://ggfx.data-imaginist.com/articles/geoms.html for confidence intervals is not useful (sorry, I don't want to be harsh).

To explain: 
Blurring should result in a figure in which regions with the same confidence interval level have the same color density/opacity/brightness.

Some thing like this, just smoother:
p = ggplot(mpg, aes(displ, hwy)) 
for (l in seq(5,95,5)/100) 
  p = p + geom_smooth(level = l, alpha = .1, fill = "blue", method = "loess", size = 0)
p

cheers - Guido

**Comment by thomasp85** [comment]
I know it is not useful. I'd be hard pressed to point to any of the examples in the documentation that shows a best practice. The purpose is to show how to use the API, not to educate on data viz🙂
